# Generated by Django 6.0 on 2026-01-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0002_task_is_deleted_taskinstance_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
