# Generated by Django 6.0 on 2026-01-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0003_taskinstance_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='remarks',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
