# Generated by Django 6.0 on 2026-01-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0005_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
