# Generated by Django 6.0 on 2026-03-05 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TODO", "0005_emailotp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="endTime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="startTime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskinstance",
            name="endTime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskinstance",
            name="startTime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Goals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_title", models.CharField(max_length=300)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("URGENT", "Urgent"),
                            ("HIGH", "High"),
                            ("MODERATE", "Moderate"),
                            ("LOW", "Low"),
                        ],
                        default="HIGH",
                        max_length=10,
                    ),
                ),
                ("priority_order", models.PositiveSmallIntegerField(default=2)),
                ("deadline", models.DateField()),
                ("isDone", models.BooleanField(default=False)),
                ("isDelete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority_order", "deadline"],
            },
        ),
    ]
