# Generated by Django 6.0 on 2026-03-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TODO", "0006_task_endtime_task_starttime_taskinstance_endtime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskinstance",
            name="endTime",
        ),
        migrations.RemoveField(
            model_name="taskinstance",
            name="startTime",
        ),
    ]
