# Generated by Django 6.0 on 2026-03-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TODO", "0007_remove_taskinstance_endtime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
