# Generated by Django 6.0 on 2026-03-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TODO", "0009_cointransaction_coinwallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinwallet",
            name="balance",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
