# Generated by Django 6.0 on 2026-03-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TODO", "0010_alter_coinwallet_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cointransaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("task", "Task Completion"),
                    ("goal", "Goal Completion"),
                    ("login", "Daily Login"),
                    ("streak", "Streak Bonus"),
                    ("undo", "Undo Task"),
                    ("notInTime", "Not done within the time"),
                ],
                max_length=20,
            ),
        ),
    ]
